// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	crawlerer "github.com/t0pep0/GB_best_go1/crawlerer"
)

// Crawler is an autogenerated mock type for the Crawler type
type Crawler struct {
	mock.Mock
}

// ChanResult provides a mock function with given fields:
func (_m *Crawler) ChanResult() <-chan crawlerer.CrawlResult {
	ret := _m.Called()

	var r0 <-chan crawlerer.CrawlResult
	if rf, ok := ret.Get(0).(func() <-chan crawlerer.CrawlResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan crawlerer.CrawlResult)
		}
	}

	return r0
}

// Scan provides a mock function with given fields: ctx, url, parentUrl, maxDepth, depth
func (_m *Crawler) Scan(ctx context.Context, url string, parentUrl string, maxDepth *int64, depth int64) {
	_m.Called(ctx, url, parentUrl, maxDepth, depth)
}

// ToChanResult provides a mock function with given fields: _a0
func (_m *Crawler) ToChanResult(_a0 crawlerer.CrawlResult) {
	_m.Called(_a0)
}
